-- MySQL Script generated by MySQL Workbench
-- Sun Apr 19 20:13:58 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema archaeo_llm_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema archaeo_llm_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `archaeo_llm_db` DEFAULT CHARACTER SET utf8 ;
USE `archaeo_llm_db` ;

-- -----------------------------------------------------
-- Table `archaeo_llm_db`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `archaeo_llm_db`.`category` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `archaeo_llm_db`.`site`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `archaeo_llm_db`.`site` (
  `site_id` INT NOT NULL AUTO_INCREMENT,
  `site_name` VARCHAR(150) NOT NULL,
  `country` VARCHAR(200) NOT NULL,
  `region` VARCHAR(150) NOT NULL,
  `latitude` DECIMAL(9,6) NOT NULL,
  `longitude` DECIMAL(9,6) NOT NULL,
  `description` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`site_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `archaeo_llm_db`.`artifact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `archaeo_llm_db`.`artifact` (
  `artifact_id` INT NOT NULL AUTO_INCREMENT,
  `category_id` INT NOT NULL,
  `site_id` INT NOT NULL,
  `inventory_code` VARCHAR(50) NOT NULL,
  `title` VARCHAR(200) NOT NULL,
  `period_name` VARCHAR(100) NOT NULL,
  `estimated_date` VARCHAR(100) NOT NULL,
  `short_description` VARCHAR(500) NULL,
  PRIMARY KEY (`artifact_id`),
  UNIQUE INDEX `inventory_code_UNIQUE` (`inventory_code` ASC) VISIBLE,
  INDEX `fk_artifact_category_idx` (`category_id` ASC) VISIBLE,
  INDEX `fk_artifact_site_idx` (`site_id` ASC) VISIBLE,
  CONSTRAINT `fk_artifact_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `archaeo_llm_db`.`category` (`category_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_artifact_site`
    FOREIGN KEY (`site_id`)
    REFERENCES `archaeo_llm_db`.`site` (`site_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `archaeo_llm_db`.`photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `archaeo_llm_db`.`photo` (
  `photo_id` INT NOT NULL AUTO_INCREMENT,
  `artifact_id` INT NOT NULL,
  `file_name` VARCHAR(255) NOT NULL,
  `alt_text` VARCHAR(255) NULL,
  `is_primary` TINYINT(1) NOT NULL,
  PRIMARY KEY (`photo_id`),
  INDEX `fk_photo_artifact_idx` (`artifact_id` ASC) VISIBLE,
  CONSTRAINT `fk_photo_artifact`
    FOREIGN KEY (`artifact_id`)
    REFERENCES `archaeo_llm_db`.`artifact` (`artifact_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `archaeo_llm_db`.`material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `archaeo_llm_db`.`material` (
  `material_id` INT NOT NULL AUTO_INCREMENT,
  `material_name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(300) NULL,
  PRIMARY KEY (`material_id`),
  UNIQUE INDEX `material_name_UNIQUE` (`material_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `archaeo_llm_db`.`artifact_material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `archaeo_llm_db`.`artifact_material` (
  `artifact_id` INT NOT NULL,
  `material_id` INT NOT NULL,
  `note` VARCHAR(200) NULL,
  PRIMARY KEY (`artifact_id`, `material_id`),
  INDEX `fk_artifactmaterial_material_idx` (`material_id` ASC) VISIBLE,
  CONSTRAINT `fk_artifactmaterial_artifact`
    FOREIGN KEY (`artifact_id`)
    REFERENCES `archaeo_llm_db`.`artifact` (`artifact_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_artifactmaterial_material`
    FOREIGN KEY (`material_id`)
    REFERENCES `archaeo_llm_db`.`material` (`material_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `archaeo_llm_db`.`artifact_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `archaeo_llm_db`.`artifact_detail` (
  `artifact_id` INT NOT NULL,
  `weight_g` DECIMAL(10,2) NULL,
  `height_mm` DECIMAL(10,2) NULL,
  `width_mm` DECIMAL(10,2) NULL,
  `condition_state` VARCHAR(100) NULL,
  `discovery_year` INT NULL,
  `detailed_description` VARCHAR(1000) NULL,
  PRIMARY KEY (`artifact_id`),
  CONSTRAINT `fk_artifactdetail_artifact`
    FOREIGN KEY (`artifact_id`)
    REFERENCES `archaeo_llm_db`.`artifact` (`artifact_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
